export const START_FETCHING_LISTS_GENRES =
  'redux/lists/START_FETCHING_LISTS_GENRES';
export const SUCCESS_FETCHING_LISTS_GENRES =
  'redux/lists/SUCCESS_FETCHING_LISTS_GENRES';
export const ERROR_FETCHING_LISTS_GENRES =
  'redux/lists/ERROR_FETCHING_LISTS_GENRES';

export const START_FETCHING_LISTS_KOMIKS =
  'redux/lists/START_FETCHING_LISTS_KOMIKS';
export const SUCCESS_FETCHING_LISTS_KOMIKS =
  'redux/lists/SUCCESS_FETCHING_LISTS_KOMIKS';
export const ERROR_FETCHING_LISTS_KOMIKS =
  'redux/lists/ERROR_FETCHING_LISTS_KOMIKS';
