export const START_FETCHING_USER = 'redux/user/START_FETCHING_USER';
export const SUCCESS_FETCHING_USER = 'redux/user/SUCCESS_FETCHING_USER';
export const ERROR_FETCHING_USER = 'redux/user/ERROR_FETCHING_USER';
